// <auto-generated />
using System;
using CKD_AI_CDSS.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CKD_AI_CDSS.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260620221519_InitialCreate-fixed")]
    partial class InitialCreatefixed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CKD_AI_CDSS.Domain.Entites.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("CKD_AI_CDSS.Domain.Entites.ChatbotSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("ChatbotSessions", (string)null);
                });

            modelBuilder.Entity("CKD_AI_CDSS.Domain.Entites.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClinicName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Specialization")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Doctors", (string)null);
                });

            modelBuilder.Entity("CKD_AI_CDSS.Domain.Entites.LabReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Albumin")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("BloodPressure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Creatinine")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal?>("Egfr")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Glucose")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal?>("Hemoglobin")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Potassium")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal?>("Sodium")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Urea")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("LabReports", (string)null);
                });

            modelBuilder.Entity("CKD_AI_CDSS.Domain.Entites.MonitoringHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("PredictionId")
                        .HasColumnType("int");

                    b.Property<int?>("PredictionId1")
                        .HasColumnType("int");

                    b.Property<int?>("PredictionId2")
                        .HasColumnType("int");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("int");

                    b.Property<string>("RiskLevelSnapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrendIndicator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("PredictionId");

                    b.HasIndex("PredictionId1");

                    b.HasIndex("PredictionId2")
                        .IsUnique()
                        .HasFilter("[PredictionId2] IS NOT NULL");

                    b.ToTable("MonitoringHistory", (string)null);
                });

            modelBuilder.Entity("CKD_AI_CDSS.Domain.Entites.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("CKD_AI_CDSS.Domain.Entites.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<decimal?>("BMI")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("LifestyleInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedicalHistory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symptoms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Patients", (string)null);
                });

            modelBuilder.Entity("CKD_AI_CDSS.Domain.Entites.Prediction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("LabReportId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<decimal>("ProbabilityScore")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("ProgressionEstimate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RetinalAnalysisId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReviewTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReviewedBy")
                        .HasColumnType("int");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShapValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LabReportId");

                    b.HasIndex("PatientId");

                    b.HasIndex("RetinalAnalysisId");

                    b.HasIndex("ReviewedBy");

                    b.ToTable("Predictions", (string)null);
                });

            modelBuilder.Entity("CKD_AI_CDSS.Domain.Entites.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("CKD_AI_CDSS.Domain.Entites.RetinalAnalysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FeatureImportance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Features")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeatmapPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RetinalImageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RetinalImageId")
                        .IsUnique();

                    b.ToTable("RetinalAnalysis", (string)null);
                });

            modelBuilder.Entity("CKD_AI_CDSS.Domain.Entites.RetinalImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Pending");

                    b.Property<int>("UploadedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("UploadedBy");

                    b.ToTable("RetinalImages", (string)null);
                });

            modelBuilder.Entity("CKD_AI_CDSS.Domain.Entites.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("CKD_AI_CDSS.Domain.Entites.AuditLog", b =>
                {
                    b.HasOne("CKD_AI_CDSS.Domain.Entites.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CKD_AI_CDSS.Domain.Entites.ChatbotSession", b =>
                {
                    b.HasOne("CKD_AI_CDSS.Domain.Entites.Patient", "Patient")
                        .WithMany("ChatbotSessions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("CKD_AI_CDSS.Domain.Entites.Doctor", b =>
                {
                    b.HasOne("CKD_AI_CDSS.Domain.Entites.User", "User")
                        .WithOne("Doctor")
                        .HasForeignKey("CKD_AI_CDSS.Domain.Entites.Doctor", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CKD_AI_CDSS.Domain.Entites.LabReport", b =>
                {
                    b.HasOne("CKD_AI_CDSS.Domain.Entites.Patient", "Patient")
                        .WithMany("LabReports")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("CKD_AI_CDSS.Domain.Entites.MonitoringHistory", b =>
                {
                    b.HasOne("CKD_AI_CDSS.Domain.Entites.Patient", "Patient")
                        .WithMany("MonitoringHistories")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CKD_AI_CDSS.Domain.Entites.Prediction", "Prediction")
                        .WithMany()
                        .HasForeignKey("PredictionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CKD_AI_CDSS.Domain.Entites.Prediction", null)
                        .WithMany("MonitoringHistories")
                        .HasForeignKey("PredictionId1");

                    b.HasOne("CKD_AI_CDSS.Domain.Entites.Prediction", null)
                        .WithOne("MonitoringHistory")
                        .HasForeignKey("CKD_AI_CDSS.Domain.Entites.MonitoringHistory", "PredictionId2");

                    b.Navigation("Patient");

                    b.Navigation("Prediction");
                });

            modelBuilder.Entity("CKD_AI_CDSS.Domain.Entites.Notification", b =>
                {
                    b.HasOne("CKD_AI_CDSS.Domain.Entites.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CKD_AI_CDSS.Domain.Entites.Patient", b =>
                {
                    b.HasOne("CKD_AI_CDSS.Domain.Entites.User", "User")
                        .WithOne("Patient")
                        .HasForeignKey("CKD_AI_CDSS.Domain.Entites.Patient", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CKD_AI_CDSS.Domain.Entites.Prediction", b =>
                {
                    b.HasOne("CKD_AI_CDSS.Domain.Entites.LabReport", "LabReport")
                        .WithMany()
                        .HasForeignKey("LabReportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CKD_AI_CDSS.Domain.Entites.Patient", "Patient")
                        .WithMany("Predictions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CKD_AI_CDSS.Domain.Entites.RetinalAnalysis", "RetinalAnalysis")
                        .WithMany()
                        .HasForeignKey("RetinalAnalysisId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CKD_AI_CDSS.Domain.Entites.Doctor", "ReviewedByDoctor")
                        .WithMany("ReviewedPredictions")
                        .HasForeignKey("ReviewedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LabReport");

                    b.Navigation("Patient");

                    b.Navigation("RetinalAnalysis");

                    b.Navigation("ReviewedByDoctor");
                });

            modelBuilder.Entity("CKD_AI_CDSS.Domain.Entites.RefreshToken", b =>
                {
                    b.HasOne("CKD_AI_CDSS.Domain.Entites.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CKD_AI_CDSS.Domain.Entites.RetinalAnalysis", b =>
                {
                    b.HasOne("CKD_AI_CDSS.Domain.Entites.RetinalImage", "RetinalImage")
                        .WithOne("RetinalAnalysis")
                        .HasForeignKey("CKD_AI_CDSS.Domain.Entites.RetinalAnalysis", "RetinalImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RetinalImage");
                });

            modelBuilder.Entity("CKD_AI_CDSS.Domain.Entites.RetinalImage", b =>
                {
                    b.HasOne("CKD_AI_CDSS.Domain.Entites.Patient", "Patient")
                        .WithMany("RetinalImages")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CKD_AI_CDSS.Domain.Entites.User", "UploadedDoctor")
                        .WithMany()
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("UploadedDoctor");
                });

            modelBuilder.Entity("CKD_AI_CDSS.Domain.Entites.Doctor", b =>
                {
                    b.Navigation("ReviewedPredictions");
                });

            modelBuilder.Entity("CKD_AI_CDSS.Domain.Entites.Patient", b =>
                {
                    b.Navigation("ChatbotSessions");

                    b.Navigation("LabReports");

                    b.Navigation("MonitoringHistories");

                    b.Navigation("Predictions");

                    b.Navigation("RetinalImages");
                });

            modelBuilder.Entity("CKD_AI_CDSS.Domain.Entites.Prediction", b =>
                {
                    b.Navigation("MonitoringHistories");

                    b.Navigation("MonitoringHistory");
                });

            modelBuilder.Entity("CKD_AI_CDSS.Domain.Entites.RetinalImage", b =>
                {
                    b.Navigation("RetinalAnalysis");
                });

            modelBuilder.Entity("CKD_AI_CDSS.Domain.Entites.User", b =>
                {
                    b.Navigation("Doctor");

                    b.Navigation("Patient");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
